import React from 'react';
import { Image, StyleSheet, View } from 'react-native';

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    position: 'absolute',
  },
  forest: {
    position: 'absolute',
    width: 20,
    height: 30,
    resizeMode: 'contain',
    zIndex: 500,
  },
  // Static styles for 100 forest positions
  forest1Style: { top: '35%', left: '10%' },
  forest2Style: { top: '65%', left: '72%' },
  forest3Style: { top: '48%', left: '58%' },
  forest4Style: { top: '50%', left: '30%' },
  forest5Style: { top: '40%', left: '65%' },
  forest6Style: { top: '60%', left: '20%' },
  forest7Style: { top: '45%', left: '78%' },
  forest8Style: { top: '32%', left: '8%' },
  forest9Style: { top: '68%', left: '45%' },
  forest10Style: { top: '55%', left: '1%' },
  forest11Style: { top: '38%', left: '52%' },
  forest12Style: { top: '59%', left: '33%' },
  forest13Style: { top: '42%', left: '69%' },
  forest14Style: { top: '61%', left: '19%' },
  forest15Style: { top: '52%', left: '79%' },
  forest16Style: { top: '30%', left: '24%' },
  forest17Style: { top: '70%', left: '52%' },
  forest18Style: { top: '44%', left: '14%' },
  forest19Style: { top: '66%', left: '61%' },
  forest20Style: { top: '37%', left: '47%' },
  forest21Style: { top: '33%', left: '59%' },
  forest22Style: { top: '58%', left: '11%' },
  forest23Style: { top: '47%', left: '46%' },
  forest24Style: { top: '62%', left: '22%' },
  forest25Style: { top: '49%', left: '35%' },
  forest26Style: { top: '31%', left: '50%' },
  forest27Style: { top: '69%', left: '19%' },
  forest28Style: { top: '41%', left: '41%' },
  forest29Style: { top: '54%', left: '26%' },
  forest30Style: { top: '36%', left: '38%' },
  forest31Style: { top: '63%', left: '52%' },
  forest32Style: { top: '46%', left: '12%' },
  forest33Style: { top: '57%', left: '34%' },
  forest34Style: { top: '39%', left: '21%' },
  forest35Style: { top: '64%', left: '45%' },
  forest36Style: { top: '43%', left: '56%' },
  forest37Style: { top: '67%', left: '17%' },
  forest38Style: { top: '34%', left: '44%' },
  forest39Style: { top: '51%', left: '30%' },
  forest40Style: { top: '60%', left: '5%' },
  forest41Style: { top: '45%', left: '10%' },
  forest42Style: { top: '68%', left: '35%' },
  forest43Style: { top: '52%', left: '55%' },
  forest44Style: { top: '75%', left: '20%' },
  forest45Style: { top: '41%', left: '62%' },
  forest46Style: { top: '60%', left: '48%' },
  forest47Style: { top: '70%', left: '15%' },
  forest48Style: { top: '48%', left: '65%' },
  forest49Style: { top: '63%', left: '30%' },
  forest50Style: { top: '50%', left: '5%' },
  forest51Style: { top: '75.6%', left: '55.3%' },
  forest52Style: { top: '44.8%', left: '19.9%' },
  forest53Style: { top: '56.1%', left: '42.0%' },
  forest54Style: { top: '68.7%', left: '2.5%' },
  forest55Style: { top: '41.2%', left: '51.8%' },
  forest56Style: { top: '59.5%', left: '33.1%' },
  forest57Style: { top: '49.0%', left: '12.4%' },
  forest58Style: { top: '71.3%', left: '47.6%' },
  forest59Style: { top: '38.4%', left: '26.8%' },
  forest60Style: { top: '63.9%', left: '59.1%' },
  forest61Style: { top: '52.7%', left: '29.3%' },
  forest62Style: { top: '78.2%', left: '10.5%' },
  forest63Style: { top: '45.1%', left: '44.2%' },
  forest64Style: { top: '66.4%', left: '35.7%' },
  forest65Style: { top: '57.8%', left: '17.3%' },
  forest66Style: { top: '40.0%', left: '5.6%' },
  forest67Style: { top: '72.9%', left: '52.9%' },
  forest68Style: { top: '51.5%', left: '22.1%' },
  forest69Style: { top: '65.2%', left: '49.8%' },
  forest70Style: { top: '43.3%', left: '31.6%' },
  forest71Style: { top: '79.1%', left: '24.7%' },
  forest72Style: { top: '54.6%', left: '7.1%' },
  forest73Style: { top: '62.0%', left: '40.4%' },
  forest74Style: { top: '48.5%', left: '3.8%' },
  forest75Style: { top: '70.2%', left: '57.5%' },
  forest76Style: { top: '46.7%', left: '16.2%' },
  forest77Style: { top: '58.9%', left: '28.9%' },
  forest78Style: { top: '74.1%', left: '50.1%' },
  forest79Style: { top: '39.8%', left: '36.5%' },
  forest80Style: { top: '67.0%', left: '20.7%' },
  forest81Style: { top: '53.4%', left: '45.3%' },
  forest82Style: { top: '76.8%', left: '15.9%' },
  forest83Style: { top: '42.5%', left: '54.0%' },
  forest84Style: { top: '60.8%', left: '8.3%' },
  forest85Style: { top: '47.9%', left: '39.2%' },
  forest86Style: { top: '69.3%', left: '27.4%' },
  forest87Style: { top: '55.1%', left: '56.9%' },
  forest88Style: { top: '73.5%', left: '2.8%' },
  forest89Style: { top: '44.0%', left: '18.1%' },
  forest90Style: { top: '61.6%', left: '43.5%' },
  forest91Style: { top: '50.3%', left: '25.6%' },
  forest92Style: { top: '77.7%', left: '58.8%' },
  forest93Style: { top: '41.9%', left: '11.0%' },
  forest94Style: { top: '64.5%', left: '30.2%' },
  forest95Style: { top: '53.8%', left: '5.2%' },
  forest96Style: { top: '71.9%', left: '46.1%' },
  forest97Style: { top: '38.9%', left: '59.7%' },
  forest98Style: { top: '67.8%', left: '14.5%' },
  forest99Style: { top: '45.8%', left: '48.3%' },
  forest100Style: { top: '62.1%', left: '73.5%' },
});

const forestData = [
  { key: 'forest_1', source: require('@/assets/images/forests/forest1.png'), style: styles.forest1Style },
  { key: 'forest_2', source: require('@/assets/images/forests/forest2.png'), style: styles.forest2Style },
  { key: 'forest_3', source: require('@/assets/images/forests/forest3.png'), style: styles.forest3Style },
  { key: 'forest_4', source: require('@/assets/images/forests/forest4.png'), style: styles.forest4Style },
  { key: 'forest_5', source: require('@/assets/images/forests/forest5.png'), style: styles.forest5Style },
  { key: 'forest_6', source: require('@/assets/images/forests/line.png'), style: styles.forest6Style },
  { key: 'forest_7', source: require('@/assets/images/forests/line2.png'), style: styles.forest7Style },
  { key: 'forest_8', source: require('@/assets/images/forests/forest1.png'), style: styles.forest8Style },
  { key: 'forest_9', source: require('@/assets/images/forests/forest2.png'), style: styles.forest9Style },
  { key: 'forest_10', source: require('@/assets/images/forests/forest3.png'), style: styles.forest10Style },
  { key: 'forest_11', source: require('@/assets/images/forests/forest4.png'), style: styles.forest11Style },
  { key: 'forest_12', source: require('@/assets/images/forests/forest5.png'), style: styles.forest12Style },
  { key: 'forest_13', source: require('@/assets/images/forests/line.png'), style: styles.forest13Style },
  { key: 'forest_14', source: require('@/assets/images/forests/line2.png'), style: styles.forest14Style },
  { key: 'forest_15', source: require('@/assets/images/forests/forest1.png'), style: styles.forest15Style },
  { key: 'forest_16', source: require('@/assets/images/forests/forest2.png'), style: styles.forest16Style },
  { key: 'forest_17', source: require('@/assets/images/forests/forest3.png'), style: styles.forest17Style },
  { key: 'forest_18', source: require('@/assets/images/forests/forest4.png'), style: styles.forest18Style },
  { key: 'forest_19', source: require('@/assets/images/forests/forest5.png'), style: styles.forest19Style },
  { key: 'forest_20', source: require('@/assets/images/forests/line.png'), style: styles.forest20Style },
  { key: 'forest_21', source: require('@/assets/images/forests/forest1.png'), style: styles.forest21Style },
  { key: 'forest_22', source: require('@/assets/images/forests/forest2.png'), style: styles.forest22Style },
  { key: 'forest_23', source: require('@/assets/images/forests/forest3.png'), style: styles.forest23Style },
  { key: 'forest_24', source: require('@/assets/images/forests/forest4.png'), style: styles.forest24Style },
  { key: 'forest_25', source: require('@/assets/images/forests/forest5.png'), style: styles.forest25Style },
  { key: 'forest_26', source: require('@/assets/images/forests/line.png'), style: styles.forest26Style },
  { key: 'forest_27', source: require('@/assets/images/forests/line2.png'), style: styles.forest27Style },
  { key: 'forest_28', source: require('@/assets/images/forests/forest1.png'), style: styles.forest28Style },
  { key: 'forest_29', source: require('@/assets/images/forests/forest2.png'), style: styles.forest29Style },
  { key: 'forest_30', source: require('@/assets/images/forests/forest3.png'), style: styles.forest30Style },
  { key: 'forest_31', source: require('@/assets/images/forests/forest4.png'), style: styles.forest31Style },
  { key: 'forest_32', source: require('@/assets/images/forests/forest5.png'), style: styles.forest32Style },
  { key: 'forest_33', source: require('@/assets/images/forests/line.png'), style: styles.forest33Style },
  { key: 'forest_34', source: require('@/assets/images/forests/line2.png'), style: styles.forest34Style },
  { key: 'forest_35', source: require('@/assets/images/forests/forest1.png'), style: styles.forest35Style },
  { key: 'forest_36', source: require('@/assets/images/forests/forest2.png'), style: styles.forest36Style },
  { key: 'forest_37', source: require('@/assets/images/forests/forest3.png'), style: styles.forest37Style },
  { key: 'forest_38', source: require('@/assets/images/forests/forest4.png'), style: styles.forest38Style },
  { key: 'forest_39', source: require('@/assets/images/forests/forest5.png'), style: styles.forest39Style },
  { key: 'forest_40', source: require('@/assets/images/forests/line.png'), style: styles.forest40Style },
  { key: 'forest_41', source: require('@/assets/images/forests/line3.png'), style: styles.forest41Style },
  { key: 'forest_42', source: require('@/assets/images/forests/line3.png'), style: styles.forest42Style },
  { key: 'forest_43', source: require('@/assets/images/forests/line3.png'), style: styles.forest43Style },
  { key: 'forest_44', source: require('@/assets/images/forests/line3.png'), style: styles.forest44Style },
  { key: 'forest_45', source: require('@/assets/images/forests/line3.png'), style: styles.forest45Style },
  { key: 'forest_46', source: require('@/assets/images/forests/line3.png'), style: styles.forest46Style },
  { key: 'forest_47', source: require('@/assets/images/forests/line3.png'), style: styles.forest47Style },
  { key: 'forest_48', source: require('@/assets/images/forests/line3.png'), style: styles.forest48Style },
  { key: 'forest_49', source: require('@/assets/images/forests/line3.png'), style: styles.forest49Style },
  { key: 'forest_50', source: require('@/assets/images/forests/line3.png'), style: styles.forest50Style },
  { key: 'forest_51', source: require('@/assets/images/forests/forest1.png'), style: styles.forest51Style },
  { key: 'forest_52', source: require('@/assets/images/forests/forest2.png'), style: styles.forest52Style },
  { key: 'forest_53', source: require('@/assets/images/forests/forest3.png'), style: styles.forest53Style },
  { key: 'forest_54', source: require('@/assets/images/forests/forest4.png'), style: styles.forest54Style },
  { key: 'forest_55', source: require('@/assets/images/forests/forest5.png'), style: styles.forest55Style },
  { key: 'forest_56', source: require('@/assets/images/forests/line.png'), style: styles.forest56Style },
  { key: 'forest_57', source: require('@/assets/images/forests/line2.png'), style: styles.forest57Style },
  { key: 'forest_58', source: require('@/assets/images/forests/forest1.png'), style: styles.forest58Style },
  { key: 'forest_59', source: require('@/assets/images/forests/forest2.png'), style: styles.forest59Style },
  { key: 'forest_60', source: require('@/assets/images/forests/forest3.png'), style: styles.forest60Style },
  { key: 'forest_61', source: require('@/assets/images/forests/forest4.png'), style: styles.forest61Style },
  { key: 'forest_62', source: require('@/assets/images/forests/forest5.png'), style: styles.forest62Style },
  { key: 'forest_63', source: require('@/assets/images/forests/line.png'), style: styles.forest63Style },
  { key: 'forest_64', source: require('@/assets/images/forests/line2.png'), style: styles.forest64Style },
  { key: 'forest_65', source: require('@/assets/images/forests/forest1.png'), style: styles.forest65Style },
  { key: 'forest_66', source: require('@/assets/images/forests/forest2.png'), style: styles.forest66Style },
  { key: 'forest_67', source: require('@/assets/images/forests/forest3.png'), style: styles.forest67Style },
  { key: 'forest_68', source: require('@/assets/images/forests/forest4.png'), style: styles.forest68Style },
  { key: 'forest_69', source: require('@/assets/images/forests/forest5.png'), style: styles.forest69Style },
  { key: 'forest_70', source: require('@/assets/images/forests/line.png'), style: styles.forest70Style },
  { key: 'forest_71', source: require('@/assets/images/forests/line2.png'), style: styles.forest71Style },
  { key: 'forest_72', source: require('@/assets/images/forests/forest1.png'), style: styles.forest72Style },
  { key: 'forest_73', source: require('@/assets/images/forests/forest2.png'), style: styles.forest73Style },
  { key: 'forest_74', source: require('@/assets/images/forests/forest3.png'), style: styles.forest74Style },
  { key: 'forest_75', source: require('@/assets/images/forests/forest4.png'), style: styles.forest75Style },
  { key: 'forest_76', source: require('@/assets/images/forests/forest5.png'), style: styles.forest76Style },
  { key: 'forest_77', source: require('@/assets/images/forests/line.png'), style: styles.forest77Style },
  { key: 'forest_78', source: require('@/assets/images/forests/line2.png'), style: styles.forest78Style },
  { key: 'forest_79', source: require('@/assets/images/forests/forest1.png'), style: styles.forest79Style },
  { key: 'forest_80', source: require('@/assets/images/forests/forest2.png'), style: styles.forest80Style },
  { key: 'forest_81', source: require('@/assets/images/forests/forest3.png'), style: styles.forest81Style },
  { key: 'forest_82', source: require('@/assets/images/forests/forest4.png'), style: styles.forest82Style },
  { key: 'forest_83', source: require('@/assets/images/forests/forest5.png'), style: styles.forest83Style },
  { key: 'forest_84', source: require('@/assets/images/forests/line.png'), style: styles.forest84Style },
  { key: 'forest_85', source: require('@/assets/images/forests/line2.png'), style: styles.forest85Style },
  { key: 'forest_86', source: require('@/assets/images/forests/forest1.png'), style: styles.forest86Style },
  { key: 'forest_87', source: require('@/assets/images/forests/forest2.png'), style: styles.forest87Style },
  { key: 'forest_88', source: require('@/assets/images/forests/forest3.png'), style: styles.forest88Style },
  { key: 'forest_89', source: require('@/assets/images/forests/forest4.png'), style: styles.forest89Style },
  { key: 'forest_90', source: require('@/assets/images/forests/forest5.png'), style: styles.forest90Style },
  { key: 'forest_91', source: require('@/assets/images/forests/line.png'), style: styles.forest91Style },
  { key: 'forest_92', source: require('@/assets/images/forests/line2.png'), style: styles.forest92Style },
  { key: 'forest_93', source: require('@/assets/images/forests/forest1.png'), style: styles.forest93Style },
  { key: 'forest_94', source: require('@/assets/images/forests/forest2.png'), style: styles.forest94Style },
  { key: 'forest_95', source: require('@/assets/images/forests/forest3.png'), style: styles.forest95Style },
  { key: 'forest_96', source: require('@/assets/images/forests/forest4.png'), style: styles.forest96Style },
  { key: 'forest_97', source: require('@/assets/images/forests/forest5.png'), style: styles.forest97Style },
  { key: 'forest_98', source: require('@/assets/images/forests/line.png'), style: styles.forest98Style },
  { key: 'forest_99', source: require('@/assets/images/forests/line2.png'), style: styles.forest99Style },
  { key: 'forest_100', source: require('@/assets/images/forests/line3.png'), style: styles.forest100Style },
];

const Forests = () => {
  return (
    <View style={styles.container}>
      {/* Map over the forestData array to render each place */}
      {forestData.map(item => (
        <Image
          key={item.key}
          source={item.source}
          style={[styles.forest, item.style]}
        />
      ))}
    </View>
  );
};

export default Forests;
